Videojs live seekbar added
ant-media/StreamApp pull request #124
Opened 2021-01-11 12:11 UTC by golgetahir

2021-01-11 12:18 UTC, golgetahir commented on src/main/webapp/play.html
> -			var player = videojs('video-player', {
poster deleted because the settings don't change after video initialized and at 287 poster also initialized again.

2021-02-01 12:57 UTC, mekya requested changes
Please use `videojs-http-streaming.js`  not `videojs-contrib-hls.js`

2021-02-01 12:57 UTC, mekya commented on src/main/webapp/play.html
> +  <script src="https://unpkg.com/videojs-contrib-hls.js"></script>
We need to use videojs-http-streaming. videojs-contrib-hls.js is obsolete
https://github.com/videojs/http-streaming

2022-01-11 17:14 UTC, mekya commented
Closing this one. A new PR which includes videojs update and dvr is sent.
https://github.com/ant-media/StreamApp/pull/245

2022-01-11 17:14 UTC, closed without merging