Move to AudioWorkletProcessor
ant-media/StreamApp pull request #346
Opened 2023-03-13 10:42 UTC by mustafaboleken

https://github.com/ant-media/Ant-Media-Server/issues/4761

2023-03-20 12:28 UTC, burak-58 requested changes

2023-04-03 07:40 UTC, mustafaboleken commented on src/main/webapp/js/media_manager.js
We don't need to use VolumeMeter. addModule line just handle import needs

2023-04-03 10:56 UTC, mekya requested changes
Could you please take a look at my comments?

2023-04-03 10:56 UTC, mekya commented on src/main/webapp/js/media_manager.js
> +        const mediaStream = await navigator.mediaDevices.getUserMedia({audio: true});
I think we already have the audio stream. Why are we getting the audio again? It may cause some problems if a specific audio device is selected.

2023-04-03 10:56 UTC, mekya commented on src/main/webapp/js/media_manager.js
> +        const mediaStream = await navigator.mediaDevices.getUserMedia({audio: true});
Don't use await. Please use promises.

2023-04-03 10:56 UTC, mekya commented on src/main/webapp/js/volume-meter-processor.js
> +// Copyright (c) 2022 The Chromium Authors. All rights reserved.
If we don't use soundmeter.js, we can delete it

2023-04-28 11:42 UTC, merged