Feature/bitrate test tool
ant-media/StreamApp pull request #95
Opened 2020-11-02 17:53 UTC by SelimEmre

2020-11-18 15:07 UTC, mekya requested changes

2020-11-18 15:07 UTC, mekya commented on src/main/webapp/webrtc-test-tool.html
> +	 function startPlaying() {
Play test is also a publish test. 
I think we should have just single button for testing, "Start WebRTC Testing"

We should provide both publish and play statistics at the same time. 

We should also provide some basic information about how WebRTC Testing works

2020-11-25 10:33 UTC, SelimEmre commented on src/main/webapp/webrtc-test-tool.html
> +				<span class="">Test duration(sec): </span>  <input type="number" id="test_duration" class="form-control" value="10">
Maybe we can use "phase" or "time" keyword.

2020-12-08 10:30 UTC, mekya approved these changes

2020-12-08 10:30 UTC, merged